name: auto_pr_recognition_yml

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      # - name: Get current datetime
      #   env:
      #     TZ: 'Asia/Tokyo'
      #   run: |
      #     echo "CURRENT_DATETIME=$(date +'%Y/%m/%d %H:%M:%S')" >> $GITHUB_ENV
      #     echo "CREATED_BRANCH=feature/merge_to_develop_$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      #   shell: bash

      - name: Create PR List text file
        run: |
          ./.github/shared/extract_pr_titles_and_links.sh > git_log.txt

      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/git_log.txt
          name: ${{ github.run_number }}